---
title: "EDS 241 Assignment 4"
author: "Mia Forsline"
date: "3/11/2022"
output: 
  pdf_document:
    toc: false
    number_sections: false
  html_document:
    theme: flatly
    code_folding: show
    toc: true
    toc_float: true
    number_sections: false 
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---
# Introduction 
We plan to estimate the price elasticity of demand for fresh sardines acros 56 points in 4 European countries. We will use monthly data from 2013 - 2019. 

## Data description 
Variables include: 
- `country`
- `port` 
- `year`
- `month`
- `price_euro_kg`
- `volume_sold_kg`
- `wind_m_s`

# Set up 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)

packages=c("cowplot",
           "datasets", 
           "dplyr",
           "estimatr",
           "here", 
           "ggplot2",
           "janitor",
           "stargazer", 
           "stringr",
           "tibble",
           "tidyverse",
           "tidyr", 
           "tinytex"
           )

for (i in packages) {
  if (require(i,character.only=TRUE)==FALSE) {
    install.packages(i,repos='http://cran.us.r-project.org')
  }
  else {
    require(i,character.only=TRUE)
  }
}

options(scipen=999) # not scientific notation
```

# Read in the data 
```{r}
data <- read_csv(here("data", "EU_sardines.csv"))
```

