---
title: "TIA: simulation of potential outcomes and ignorable treatments"
author: "Mia Forsline"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(ggplot2)
library(vtable)
library(stargazer)
library(estimatr)

set.seed(7307)
```


```{r}


bigN=20000

W <- runif(bigN,0,5)
X=as.integer(W+1)
X1 <- as.numeric(X==1)
X2 <- as.numeric(X==2)
X3 <- as.numeric(X==3)
X4 <- as.numeric(X==4)
X5 <- as.numeric(X==5)



# GENERATE MEAN COMPONENT OF POTENTIAL OUTCOMES
MU0=(1/2)*X1 + (2/2)*X2 + (3/2)*X3 + (4/2)*X4 + (5/2)*X5
mean(MU0)
MU1=1*X1 + 2*X2 + 3*X3 + 4*X4 + 5*X5
mean(MU1)


# GENERATE ERROR COMPONENT OF POTENTIAL OUTCOMES
Sigma <- matrix(c(1,0.75,0.75,1),2,2)
Sigma
e <- (mvrnorm(n=bigN, rep(0, 2), Sigma))
e0 <- e[,c(1)]
mean(e0)
e1 <- e[,c(2)]  
mean(e1)



# GENERATE POTENTIAL OUTCOMES
Y0 <- MU0 + e0
mean(Y0)
Y1 <- MU1 + e1
mean(Y1)

ATE <- mean(Y1)-mean(Y0)
print(ATE)

# ASSIGN A TREATMENT IGNORABLE COND ON X
v <- rnorm(bigN, 0, 2)
D <- as.numeric((-2*X1+ -1*X2 + 0.5*X3 + 1*X4 + 2*X5 + v)>0)
mean(D)


# USE SUTVA TO MAP POTENTIAL OUTCOMES INTO OBSERVED OUTCOMES
Y = D*Y1 + (1-D)*Y0


# COLLECT ALL RELEVANT VARIABLES IN A DATAFRAME
TIA_DATA <- data.frame(D, Y0, Y1, X, X1, X2, X3, X4, X5)


# SHOW THAT D IS NOT INDEPENDENT OF X, Y0, Y1 (RECALL Y0,Y1 NOT OBSERVED IN REALITY)
sumtable(TIA_DATA, vars=c('Y0','Y1', 'X1', 'X2', 'X3', 'X4', 'X5'), group='D', group.test=TRUE)


# SIMPLE OLS ESTIMATOR NOT CONSISTENT FOR ATE
ols <- lm_robust(formula = Y ~ D, data=TIA_DATA)
summary(ols)

```

