---
title: "EDS241: Simulations of consistency of OLS and omitted variable bias"
author: "Mia Forsline"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
#install.packages("ggplot2")
#install.packages("huxtable")
#install.packages("ggthemes")
library(ggplot2)
library(huxtable)
library(ggthemes)
```

```{r}
# 1. Demonstrating consistency of OLS under LSA 1-3

set.seed(420) 

bigN <- 10000 #sample size

# Generate X1 and µ
X1 <- runif(bigN, min = 0, max = 10)
u <- rnorm(bigN, mean = 0, sd = 4) #normal distribution 

# Bivariate population regression function
Y <- 5 + 1.5*X1 + u #define Y 
population_data <- data.frame(X1, Y) #create df 

# OLS estimation, full sample
## estimate B0 and B1 
model1 <- lm(formula = Y ~ X1, data = population_data)
huxreg(model1, error_pos="right")

# OLS estimation, with sample size increasing from n=1 to 10,000
betahat_output <- matrix(ncol = 2, nrow = bigN)

#loop through all sample sizes 
for (n in 1:bigN) {
  sample <- population_data[1:n,]
  betahat_output[n,] <- lm(Y ~ X1, data = sample)$coefficients
} 

n <- seq(1,bigN)
beta1hat <- betahat_output[,c(2)]
forgraph <- data.frame(n , betahat_output[,c(2)])

# Graphing the results of all 10,000 B1 hats as they approach the true B1 hat value of 1.5 
ggplot(forgraph , aes(x=n, y=beta1hat)) + geom_line(size=0.5, color="blue") +
  geom_hline(yintercept=1.5, size=2, color="red") +
  labs(x="n", y = "Beta1hat") + 
  ggthemes::theme_pander(base_size = 14) 

#as n increases, the blue line (B1 hat) approaches the red line (true B1 = 1.5)
```


# 2. Demonstrating omitted variables bias
```{r}

## now, we generate and X2 correlated with X1 
## Then we omit X2
## B1 hat will never approach the true B1 because of omitted variables bias 

X2 = X1 +rnorm(bigN , mean=0 , sd=2.2) #X2 = X1 + random number, so X2 and X1 are correlated 

# Multiple population regression function
##define Y 
Y <- 5 + 1.5*X1 + 10*X2 + u
population_data <- data.frame(X1, Y)

# OLS estimation, full sample, but ignoring X2
model1 <- lm(formula = Y ~ X1, data = population_data)
huxreg(model1, error_pos="right")

# Compute correlation between X1 and X2, and standard deviations
# Compute "probability limit" of Beta1_hat
cor(X1,X2)
sd(X1)
sd(X2)
1.5 + 10*cor(X1,X2)*sd(X2)/sd(X1)

# OLS estimation, with sample size increasing from n=1 to 10,000
betahat_output <- matrix(ncol = 2, nrow = bigN)

for (n in 1:bigN) {
  sample <- population_data[1:n,]
  betahat_output[n,] <- lm(Y ~ X1, data = sample)$coefficients
} 

n <- seq(1,bigN)
beta1hat <- betahat_output[,c(2)]
forgraph <- data.frame(n , betahat_output[,c(2)])

ggplot(forgraph , aes(x=n, y=beta1hat)) + geom_line(size=0.5, color="blue") +
  geom_hline(yintercept=1.5, size=2, color="red") +
  labs(x="n", y = "Beta1hat") + 
  ggthemes::theme_pander(base_size = 14) 
```

